[build]
  # Directorio de publicación generado por Vite (por defecto "dist")
  publish = "dist"
  
  # Comando para compilar la aplicación con Vite
  command = "npm run build"

[[redirects]]
  # Redirigir todas las rutas a "index.html" para que el enrutador de React maneje las rutas
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
